@startuml
autonumber

participant "API Gateway" as API
participant "Lambda Function" as Lambda
participant "Database" as Aurora
participant "SQS Audit Queue" as SQS_Audit

API -> Lambda: POST /otp/verify (headers, body)
Lambda -> Lambda: Genera request_id y obtiene path

alt Falta X-UserId
    Lambda -> API: Retorna 400 (MISSING_HEADERS)
else Falta OTP o transaction_type
    Lambda -> API: Retorna 400 (MISSING_FIELDS)
else
    Lambda -> Aurora: Consulta OTP (por otp, transaction_type, usuario y estado activo) en la BD
    Aurora -> Lambda: Retorna resultado de consulta
    Lambda -> Lambda: Validar la vigencia del ultimo OTP enviado por usuario [Current Date - Sent Date <= 24hrs]
    alt OTP válido
        Lambda -> Aurora: Marca OTP como usado
        Aurora -> Lambda: Confirmación de actualización
        Lambda -> SQS_Audit: Guarda evento de éxito en auditoría
        Lambda -> API: Retorna 204 (No Content)
    else OTP inválido o expirado
        Lambda -> SQS_Audit: Guarda error en auditoría
        Lambda -> API: Retorna 404 (OTP_NOT_FOUND)
    end
end

alt Error inesperado
    Lambda -> SQS_Audit: Guarda error interno en auditoría
    Lambda -> API: Retorna 500 (INTERNAL_ERROR)
end

@enduml