@startuml
autonumber

participant "API Gateway" as API
participant "Authorizer Lambda" as Handler
participant "CognitoClient" as Cognito
participant "API Gateway" as APIGateway
participant "Backend" as Backend 
participant "SQSClient" as SQS


API -> Handler: handleRequest(input, context)
Handler -> Handler: Obtener headers del request
Handler -> Cognito: validate(jwt)
Cognito --> Handler: Retornar Subject (usuario autenticado)

Handler -> Handler: Extraer datos del JWT (userId, orgId, roles, email, etc.)
Handler -> Handler: Construir contexto de autorización
Handler -> Handler: Mapear contexto en estructura clave-valor
Handler -> Handler: Incluir contexto en la respuesta
APIGateway -> Handler: Mapear datos basado en respuesta authorizer [Uso de Mapping Templates]
APIGateway -> Backend: Enviar datos como Headers a Backend + Request Body

Handler -> SQS: send_audit_event(transaction_id, path, request_body, transaction_output, request_id)
SQS --> Handler: Confirmación de auditoría enviada

Handler -> API: Retornar Response con datos mapeados
@enduml